### ISSUE TITLE
some unusual errors in function values

### ISSUE THREAD

**Issue by sanjayjain159** [pahihu/ficl#1]
Dear Sir,

1e-6 fasinh fs. yields 10e-6. And 1e-6 fsin yields 10e-6. Both answers should be near 1e-6. I wonderr if it is a virus in my computer

**Comment by pahihu** [comment]
Hi,

It is a bug. If you use F. it prints the correct value. FS. and FE. is off by 10x.
I will fix it.

Regards,
pahihu

**Comment by sanjayjain159** [comment]
Thanks

BR,

SJain

**Comment by pahihu** [comment]
Hi,

Please check the new sources from GitHub, I’ve fixed it in float.c
If there was a rounding, sometimes it added one more digit to the required precision.
I hope, I’ve fixed it. Your example works, as expected.

Regards,
pahihu

**Comment by sanjayjain159** [comment]
Thank you, Sir.
